try:
    number=one
    print("the number is ",number)
except NameError as ex:
    print("Exception is: ", ex)

